In [134]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


df=pd.read_csv("heart_update.csv")
df.drop('Unnamed: 0',axis=1,inplace=True)
df.head()

male  age  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39              0         0.0     0.0                0   
1     0   46              0         0.0     0.0                0   
2     1   48              1        20.0     0.0                0   
3     0   61              1        30.0     0.0                0   
4     0   46              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [135]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]
x

male  age  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0        1   39              0         0.0     0.0                0   
1        0   46              0         0.0     0.0                0   
2        1   48              1        20.0     0.0                0   
3        0   61              1        30.0     0.0                0   
4        0   46              1        23.0     0.0                0   
...    ...  ...            ...         ...     ...              ...   
4233     1   50              1         1.0     0.0                0   
4234     1   51              1        43.0     0.0                0   
4235     0   48              1        20.0     0.0                0   
4236     0   44              1        15.0     0.0                0   
4237     0   52              0         0.0     0.0                0   

      prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  
0                0         0    195.0  106.0   70.0  26.97       80.0     77.0  
1                0         0    250.0  121.0   81.0  28.73       95.0     76.0  
2                0         0    245.0  127.5   80.0  25.34       75.0     70.0  
3                1         0    225.0  150.0   95.0  28.58       65.0    103.0  
4                0         0    285.0  130.0   84.0  23.10       85.0     85.0  
...            ...       ...      ...    ...    ...    ...        ...      ...  
4233             1         0    313.0  179.0   92.0  25.97       66.0     86.0  
4234             0         0    207.0  126.5   80.0  19.71       65.0     68.0  
4235             0         0    248.0  131.0   72.0  22.00       84.0     86.0  
4236             0         0    210.0  126.5   87.0  19.16       86.0     78.0  
4237             0         0    269.0  133.5   83.0  21.47       80.0    107.0  

[4238 rows x 14 columns]

In [136]:
y

0       0
1       0
2       0
3       1
4       0
       ..
4233    1
4234    0
4235    0
4236    0
4237    0
Name: TenYearCHD, Length: 4238, dtype: int64

In [137]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4238 entries, 0 to 4237
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   male             4238 non-null   int64  
 1   age              4238 non-null   int64  
 2   currentSmoker    4238 non-null   int64  
 3   cigsPerDay       4238 non-null   float64
 4   BPMeds           4238 non-null   float64
 5   prevalentStroke  4238 non-null   int64  
 6   prevalentHyp     4238 non-null   int64  
 7   diabetes         4238 non-null   int64  
 8   totChol          4238 non-null   float64
 9   sysBP            4238 non-null   float64
 10  diaBP            4238 non-null   float64
 11  BMI              4238 non-null   float64
 12  heartRate        4238 non-null   float64
 13  glucose          4238 non-null   float64
 14  TenYearCHD       4238 non-null   int64  
dtypes: float64(8), int64(7)
memory usage: 496.8 KB


male               0
age                0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64

In [138]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)



In [139]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)





 # LOGISTIC REGRESSION

In [140]:
from sklearn.linear_model import LogisticRegression
model1 = LogisticRegression(multi_class='ovr')
model1.fit(x_train, y_train)
y_pred = model1.predict(x_test)
y_pred


c:\Users\amiya\OneDrive\Desktop\ML\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


array([0, 0, 0, ..., 0, 0, 0])

In [141]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
score=accuracy_score(y_test,y_pred)
score



0.8660377358490566

In [142]:
confusion_matrix(y_test,y_pred)

array([[901,   7],
       [135,  17]])

In [143]:
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.87      0.99      0.93       908\n           1       0.71      0.11      0.19       152\n\n    accuracy                           0.87      1060\n   macro avg       0.79      0.55      0.56      1060\nweighted avg       0.85      0.87      0.82      1060\n'

# GRIDSEARCHCV

In [144]:
from sklearn.linear_model import LogisticRegression
model2 = LogisticRegression(multi_class='ovr')
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()
c_values=[100,10,1,0.1,0.01]
params = [
    {"penalty": ["l1", "l2"], "solver": ["liblinear"], "C": c_values},
    {"penalty": ["l1", "l2"], "solver": ["saga"], "C": c_values},
    {"penalty": ["elasticnet"], "solver": ["saga"], "C": c_values, "l1_ratio": [0.0, 0.5, 1.0]}
]

grid=GridSearchCV(estimator=model2,cv=cv,param_grid=params,n_jobs=-1,scoring="accuracy")
grid.fit(x_train,y_train)
y_pred2=grid.predict(x_test)

c:\Users\amiya\OneDrive\Desktop\ML\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


In [145]:
y_pred2

array([0, 0, 0, ..., 0, 0, 0])

In [146]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
score=accuracy_score(y_test,y_pred2)
score


0.8660377358490566

In [147]:
confusion_matrix(y_test,y_pred2)

array([[903,   5],
       [137,  15]])

In [148]:
classification_report(y_test,y_pred2)

'              precision    recall  f1-score   support\n\n           0       0.87      0.99      0.93       908\n           1       0.75      0.10      0.17       152\n\n    accuracy                           0.87      1060\n   macro avg       0.81      0.55      0.55      1060\nweighted avg       0.85      0.87      0.82      1060\n'

# RANDOMIZEDSEARCH-CV

In [149]:
from sklearn.linear_model import LogisticRegression
model3 = LogisticRegression(multi_class='ovr')
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()
c_values=[100,10,1,0.1,0.01]
params = [
    {"penalty": ["l1", "l2"], "solver": ["liblinear"], "C": c_values},
    {"penalty": ["l1", "l2"], "solver": ["saga"], "C": c_values},
    {"penalty": ["elasticnet"], "solver": ["saga"], "C": c_values, "l1_ratio": [0.0, 0.5, 1.0]}
]

random=GridSearchCV(estimator=model2,cv=cv,param_grid=params,n_jobs=-1,scoring="accuracy")
random.fit(x_train,y_train)
y_pred3=random.predict(x_test)

c:\Users\amiya\OneDrive\Desktop\ML\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


In [150]:
y_pred3

array([0, 0, 0, ..., 0, 0, 0])

In [151]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
score=accuracy_score(y_test,y_pred3)

In [152]:
score

0.8660377358490566

In [153]:
confusion_matrix(y_test,y_pred3)

array([[903,   5],
       [137,  15]])

In [154]:
classification_report(y_test,y_pred3)

'              precision    recall  f1-score   support\n\n           0       0.87      0.99      0.93       908\n           1       0.75      0.10      0.17       152\n\n    accuracy                           0.87      1060\n   macro avg       0.81      0.55      0.55      1060\nweighted avg       0.85      0.87      0.82      1060\n'

In [ ]:
# import pickle
# pickle.dump(scaler,open("scaler.pkl","wb"))
# pickle.dump(random,open("model.pkl","wb"))